version: "3.7"
services:
    desarrollo:
        container_name: desa-app
        restart: always
        build: .
        ports:
            - "8081:80"
        environment:
            - NODE_ENV=development
    produccion:
        container_name: prod-app
        restart: always
        build: .
        ports:
            - "8082:80"
        environment:
            - NODE_ENV=production
